disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - function_parameter_count
  - function_body_length
  - trailing_whitespace
  - line_length
  - file_length
  - cyclomatic_complexity
  - todo
opt_in_rules:
  - force_unwrapping
included:
    - ../fcm-channel-ios
excluded:
  - Pods
  - Pods/Deve
line_length: 110
# they can set both implicitly with an array
force_unwrapping:
    severity: error
type_body_length:
- 300 # warning
- 1200 # error
