use_frameworks!

target 'fcm-channel-ios_Example' do
  pod 'fcm-channel-ios', :path => '../'

  pod 'SwiftLint'

  pod 'FBSDKLoginKit', '4.23.0'
  pod 'FBSDKCoreKit', '4.23.0'

  pod 'Firebase/Core', '5.20.2'
  pod 'Firebase/Messaging', '5.20.2'
  pod 'Firebase/Auth', '5.20.2'
  pod 'Firebase/Database', '5.20.2'

  pod 'AlamofireObjectMapper', '5.2.0'
  pod 'Alamofire', '4.9.0'
  pod 'MDHTMLLabel', '1.0.2'
  pod 'MBProgressHUD', '1.1.0'
  pod 'TPKeyboardAvoiding', '1.3.2'
  pod 'ISScrollViewPageSwift', '1.0.0'

  target 'fcm-channel-ios_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  legacy_swift_pods = [
    'Alamofire',
    'AlamofireObjectMapper',
    'ObjectMapper',
  ]

  installer.pods_project.targets.each do |target|
    if legacy_swift_pods.include? target.name
      target.build_configurations.each do |config|
        Pod::UI.puts "Fixing #{target}(#{config})"
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
